# Generated by Django 5.2.5 on 2025-10-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ukulele', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, verbose_name='Napíš niečo o sebe'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dalsi_nastroj',
            field=models.CharField(blank=True, max_length=50, verbose_name='Na aký ďalší hudobný nástroj sa učíš hrať ?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ladenie',
            field=models.CharField(max_length=50, verbose_name='Aké ladenie najradšej používaš ?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='typ_ukulele',
            field=models.CharField(max_length=50, verbose_name='Aký typ ukulele máš ?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='znacka_strun',
            field=models.CharField(max_length=50, verbose_name='Akú značku strún používaš ?'),
        ),
    ]
