

FRETBOARD_NOTES = [
    {'string': 'A', 'note': 'A#/Bb'},
    {'string': 'A', 'note': 'B'},
    {'string': 'A', 'note': 'C'},
    {'string': 'A', 'note': 'C#/Db'},
    {'string': 'A', 'note': 'D'},
    {'string': 'A', 'note': 'D#/Eb'},
    {'string': 'A', 'note': 'E'},
    {'string': 'A', 'note': 'F'},
    {'string': 'A', 'note': 'F#/Gb'},
    {'string': 'A', 'note': 'G'},
    {'string': 'A', 'note': 'G#/Ab'},
    {'string': 'A', 'note': 'A'},

    {'string': 'E', 'note': 'E#/F'},
    {'string': 'E', 'note': 'F#/Gb'},
    {'string': 'E', 'note': 'G'},
    {'string': 'E', 'note': 'G#/Ab'},
    {'string': 'E', 'note': 'A'},
    {'string': 'E', 'note': 'A#/Bb'},
    {'string': 'E', 'note': 'B'},
    {'string': 'E', 'note': 'C'},
    {'string': 'E', 'note': 'C#/Db'},
    {'string': 'E', 'note': 'D'},
    {'string': 'E', 'note': 'D#/Eb'},
    {'string': 'E', 'note': 'E'},

    {'string': 'C', 'note': 'C#/Db'},
    {'string': 'C', 'note': 'D'},
    {'string': 'C', 'note': 'D#/Eb'},
    {'string': 'C', 'note': 'E'},
    {'string': 'C', 'note': 'F'},
    {'string': 'C', 'note': 'F#/Gb'},
    {'string': 'C', 'note': 'G'},
    {'string': 'C', 'note': 'G#/Ab'},
    {'string': 'C', 'note': 'A'},
    {'string': 'C', 'note': 'A#/Bb'},
    {'string': 'C', 'note': 'B'},
    {'string': 'C', 'note': 'C'},

    {'string': 'G', 'note': 'G#/Ab'},
    {'string': 'G', 'note': 'A'},
    {'string': 'G', 'note': 'A#/Bb'},
    {'string': 'G', 'note': 'B'},
    {'string': 'G', 'note': 'C'},
    {'string': 'G', 'note': 'C#/Db'},
    {'string': 'G', 'note': 'D'},
    {'string': 'G', 'note': 'D#/Eb'},
    {'string': 'G', 'note': 'E'},
    {'string': 'G', 'note': 'F'},
    {'string': 'G', 'note': 'F#/Gb'},
    {'string': 'G', 'note': 'G'},
]